// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySZpx_yMkoyZsYJrrvLdzMpf_sE6Kkzk',
    appId: '1:266915764306:web:b66c6834704fba560b278b',
    messagingSenderId: '266915764306',
    projectId: 'yobante1',
    authDomain: 'yobante1.firebaseapp.com',
    storageBucket: 'yobante1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jZA5ez7Y1t-_F8aZEl40qgnGkc8NdoQ',
    appId: '1:266915764306:android:0f0e92c2d13aa83f0b278b',
    messagingSenderId: '266915764306',
    projectId: 'yobante1',
    storageBucket: 'yobante1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7kUwLzNw1IihCjjYluR5fAKBtZSSoZE',
    appId: '1:266915764306:ios:1eeccdd00a9efc1f0b278b',
    messagingSenderId: '266915764306',
    projectId: 'yobante1',
    storageBucket: 'yobante1.appspot.com',
    iosBundleId: 'com.example.newDance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7kUwLzNw1IihCjjYluR5fAKBtZSSoZE',
    appId: '1:266915764306:ios:1eeccdd00a9efc1f0b278b',
    messagingSenderId: '266915764306',
    projectId: 'yobante1',
    storageBucket: 'yobante1.appspot.com',
    iosBundleId: 'com.example.newDance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAySZpx_yMkoyZsYJrrvLdzMpf_sE6Kkzk',
    appId: '1:266915764306:web:8fedffabdeedefca0b278b',
    messagingSenderId: '266915764306',
    projectId: 'yobante1',
    authDomain: 'yobante1.firebaseapp.com',
    storageBucket: 'yobante1.appspot.com',
  );

}